server:
  port: 8080
spring:
  application:
    name: soultalk
  datasource:
#    url: jdbc:mysql://47.109.181.181:3306/soultalk?useSSL=false&serverTimezone=UTC
#    username: soultalk
#    password: a12345

#    本机测试
    username:  root
    password:  258013CH
    url: jdbc:mysql://localhost:3306/soultalk?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # 可根据需求调整

#mybatis 配置
mybatis:
  configuration:
#    日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    自动映射驼峰命名
    map-underscore-to-camel-case: true

#日志
logging:
    level:
      root: debug
